version: '3.8'

services:
  backend:
    build: ./server
    container_name: vele-server
    ports:
      - 5000:5000
    env_file:
      - ./server/.env
    
  frontend:
    build: ./client
    container_name: vele-client
    ports:
      - 3000:3000
    env_file:
      - ./client/.env
    depends_on:
      - backend
 